image: Visual Studio 2017 Preview

environment:
    matrix:   
    - channel: stable
      build: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - appveyor DownloadFile https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip -FileName nasm.zip
    - 7z e -y nasm.zip
    - rustup-init -yv --default-toolchain %channel% --default-host %target%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
    - rustc -vV
    - cargo -vV

build_script:
    - git submodule update --init
    - cargo build --release

test_script:
    - git submodule update --init
    - cargo test --verbose

artifacts:
    - path: target\release\rav1e.exe
      name: rav1e
